import React, { useRef, useState , useEffect } from 'react'
import {
    Card,
    CardBody,
} from "@material-tailwind/react";
import moment from 'moment';
import ReactToPrint from 'react-to-print';
import { useLocation } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { handlerGetAnySingleDataByID } from '@/Redux/GetAnySingleDataByID';
const TransactionDetailsPage = () => {
    const location = useLocation();
    let userId = location.search.replace("?", "")
    const dispatch = useDispatch()
    const componentRef = useRef();
    const { GetSingleDataById } = useSelector((state) => state.GetAnySingleDataByID);
    const [DisplayDownLoadButton, setDisplayDownLoadButton] = useState(true)
    


    const openInNewTab = (url) => {
        const newWindow = window.open(url, '_blank', 'noopener,noreferrer')
        if (newWindow) newWindow.opener = null
    }
    const handleOnBeforeGetContent = React.useCallback(() => {
        setLoading(true);
        setDisplayDownLoadButton(false)
        return new Promise((resolve) => {
            onBeforeGetContentResolve.current = resolve;
            setTimeout(() => {
                setDisplayDownLoadButton(true)
                resolve();
            }, 2000);
        });
    }, []);
    const onBeforeGetContentResolve = React.useRef(null);
    useEffect(() => {
        if (
            typeof onBeforeGetContentResolve.current === "function"
        ) {
            onBeforeGetContentResolve.current();
        }
    }, [onBeforeGetContentResolve.current]);

    const reactToPrintContent = React.useCallback(() => {
        return componentRef.current;
    }, [componentRef.current]);


    useEffect(() => {
        dispatch(handlerGetAnySingleDataByID({
            id:userId,
            url:"transaction"
        }))
      return () => {
      }
    }, [])
     console.log("GetSingleDataById",GetSingleDataById)
    return (
        <div className='mt-3'>
            <Card>
                <CardBody className="px-4 pt-0 pb-4">
                    <ReactToPrint
                        pageStyle={"print-page"}
                        trigger={() => <button className='d-none' id='DownloadInvoice'>Print</button>}
                        documentTitle="PBIB"
                        content={reactToPrintContent}
                        onBeforeGetContent={handleOnBeforeGetContent}
                    />
                    <section id="newInvoice" ref={componentRef}>
                        <div className="container-fluid bg-white" >
                            <div className='bg-white'>
                                <section className=' mb-4 pt-3 bg-white'>
                                    <div className='row '>
                                        <div className='col-md-12 mob-flex align-items-center justify-content-between'>
                                            <div className={` justify-content-end `}>
                                                <div className={`${DisplayDownLoadButton ? "d-flex" : "d-none"}`}>
                                                        <label htmlFor='DownloadInvoice' className={`margin-bb c_pointer middle none font-sans font-bold center uppercase transition-all disabled:opacity-50 disabled:shadow-none disabled:pointer-events-none text-xs py-3 px-6 rounded-lg bg-blue-500 text-white shadow-md shadow-blue-500/20 hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none `}>
                                                            Download
                                                        </label >
                                                </div>
                                            </div>
                                            <h5 className='mb-0 Heading'>Invoice Created: <span className="">{moment().format('MM-DD-YYYY')} </span></h5>
                                        </div>
                                    </div>
                                </section>
                                <div className='col-md-12 mb-3 mt-2'>
                                    <h6 className='headinglast'>Payment Response: </h6>
                                    <p>A payment response is a message or set of data generated by a payment processing system or gateway in response to a payment transaction. It serves to communicate the outcome and details of the payment attempt between the payment service provider and the parties involved, such as the payer (customer) and the payee (merchant).</p>
                                </div>
                                <div className="d-flex gap-5 flex-wrap">
                                    <div>
                                        <h5 className='Heading mb-2'>From</h5>
                                        <div className='mob-flex'>
                                            <div className='outerWrapperLogoImage me-4'>
                                                <img src={"/assets/icons/logo.png"} alt='PBIB' className='LogoImage' />
                                            </div>
                                            <div>
                                                <h6 className='invoiceHeading Heading'>PBIB!</h6>
                                                <p className='invoiceHeading mb-1'>Web: 
                                                    <span className="textPaymentColor c_pointer ms-1" style={{fontSize:"14px"}} onClick={() => {
                                                        openInNewTab("http://127.0.0.1:5173/dashboard/home")
                                                    }}>
                                                        http://127.0.0.1:5173/dashboard
                                                    </span></p>
                                                <h6 className='invoiceHeading mb-1'>Phone: <span className="">123 2584 4523</span></h6>
                                            </div>
                                        </div>
                                    </div>
                                    <div className=' mt-3'>
                                        <h5 className='Heading mb-2'>To</h5>
                                        <h6 className='invoiceHeading mb-1'> Timkozak </h6>
                                        <h6 className='invoiceHeading mb-1'>Email: <span className="">XYZ@gmail.com</span></h6>
                                        <h6 className='invoiceHeading mb-1'>Phone: <span className="">628162812</span></h6>
                                        <h6 className='invoiceHeading'>Address: <span className="">XYZ</span></h6>
                                    </div>
                                    <div className=''>
                                        <h6 className='invoiceHeading mt-4 Heading mb-2'>Transaction {GetSingleDataById && GetSingleDataById?.transactionID}</h6>
                                        <h6 className='invoiceHeading mb-1'>Date: <span className="">{moment(GetSingleDataById && GetSingleDataById?.DateTime).format('MM-DD-YYYY')}</span></h6>
                                        <h6 className='invoiceHeading mb-1'>Due Date: <span className="">{moment(GetSingleDataById && GetSingleDataById?.DateTime).format('MM-DD-YYYY')}</span></h6>
                                        <h6 className='invoiceHeading mb-1'>Status: <span className={`YesBadge`}>{GetSingleDataById && GetSingleDataById?.status}</span></h6>
                                        {/* <h6 className='invoiceHeading'>Total Due: <span className="">${GetAppointment?.data[0]?.Appointments?.totalpayable}</span></h6> */}
                                    </div>
                                </div>
                                <div className='row bg-white mt-3'>
                                    <div className='col-md-12 bg-white'>
                                        <div className='d-flex mb-2' style={{ justifyContent: "space-between" }}>
                                            <div>
                                                <h6 className='headinglast mb-2'>Transaction ID</h6>
                                                <h6 className='headinglast mb-2'>User ID</h6>
                                                <h6 className='headinglast mb-2'>Product ID</h6>
                                                <h6 className='headinglast mb-2'>Service ID</h6>
                                                <h6 className='headinglast mb-2'>Transaction Amount</h6>
                                                <h6 className='headinglast mb-2'>Payment Method</h6>
                                                <h6 className='headinglast mb-2'>Payment Datetime</h6>
                                                <h6 className='headinglast mb-2'>Payment Status</h6>
                                                <h6 className='headinglast mb-2'>SUBTOTAL</h6>
                                                <h6 className='headinglast mb-2'>TAX</h6>
                                                <h6 className='headinglast mb-2'>TIP</h6>
                                                <h6 className='headinglast'>TOTAL</h6>
                                            </div>
                                            <div>
                                                <h6 className='headinglast mb-2 text-end '>{GetSingleDataById && GetSingleDataById?.transactionID}</h6>
                                                <h6 className='headinglast mb-2 text-end '>{GetSingleDataById && GetSingleDataById?.userID}</h6>
                                                <h6 className='headinglast mb-2 text-end '>{GetSingleDataById && GetSingleDataById?.productID}</h6>
                                                <h6 className='headinglast mb-2 text-end '>{GetSingleDataById && GetSingleDataById?.serviceID}</h6>
                                                <h6 className='headinglast mb-2 textPaymentColor text-end '>${GetSingleDataById && GetSingleDataById?.Amount}</h6>
                                                <h6 className='headinglast mb-2 text-end '>{GetSingleDataById && GetSingleDataById?.Paymentmethod}</h6>
                                                <h6 className='headinglast mb-2 text-end '>9:59 am Thursday, 4 January 2024</h6>
                                                <div className='d-flex justify-content-end'>
                                                    <h6 className='headinglast mb-2 YesBadge text-end '>{GetSingleDataById && GetSingleDataById?.Status}</h6>
                                                </div>
                                                <h6 className='headinglast mb-2 text-end '>${GetSingleDataById && GetSingleDataById?.Amount}</h6>
                                                <h6 className='headinglast mb-2 text-end '>${GetSingleDataById && GetSingleDataById?.Amount}</h6>
                                                <h6 className='headinglast text-end '>${GetSingleDataById && GetSingleDataById?.Amount}</h6>
                                            </div>
                                        </div>
                                        <hr />
                                        <div className='d-flex mt-2' style={{ justifyContent: "space-between" }}>
                                            <div>
                                                <h4 className='finalInvoice'>Balance</h4>
                                            </div>
                                            <div>
                                                <h4 className='finalInvoice textPaymentColor'>${GetSingleDataById && GetSingleDataById?.Amount}</h4>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </CardBody>
            </Card>
        </div>
    )
}

export default TransactionDetailsPage